#!/usr/bin/env python3
"""Build the aion package from brand.config.json.

Equivalent of Proteus's build-bundle.ts but Python — much simpler because
Python doesn't need esbuild-style bundling. The "build" here means:

  1. Read brand.config.json
  2. Templatize pyproject.toml's `project.name` and `project.scripts` from
     brand.binary so a rebrand to "foo" produces a `foo-cli` package with
     a `foo` script entry point
  3. Generate `.env-active` with provider env vars from api.preset
  4. (Optional) Build a wheel for distribution via `python -m build`

After running, the user runs `pip install -e .` (dev) or `pipx install .`
(prod) and gets the brand-named binary on PATH.

Usage:
  python scripts/build.py             # templatize + generate .env-active
  python scripts/build.py --wheel     # also build a wheel artifact in dist/
  python scripts/build.py --quiet     # suppress informational output

Run from the project root (the dir containing brand.config.json).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Allow `from aion.config import ...` even before pip-install
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from aion.config import BrandConfig, load_brand_config  # noqa: E402


def log(msg: str, quiet: bool) -> None:
    if not quiet:
        print(msg)


def update_pyproject(brand: BrandConfig, root: Path, quiet: bool) -> bool:
    """Update pyproject.toml's name + scripts entry from brand.binary.

    Returns True if anything changed. Uses regex-style replacement on the
    minimal lines we care about — avoids pulling in a TOML writer dependency
    just for two field rewrites.
    """
    path = root / "pyproject.toml"
    text = path.read_text()
    original = text

    new_pkg_name = f"{brand.binary}-cli"
    new_script_line = f'{brand.binary} = "{brand.binary}.cli:main"'

    # name = "..."
    import re

    text = re.sub(
        r'^name\s*=\s*"[^"]*"\s*$',
        f'name = "{new_pkg_name}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )

    # The [project.scripts] block — replace the FIRST script entry with the brand binary.
    # Pattern matches a line like `<anyname> = "<anyname>.cli:main"` inside that block.
    # This assumes ONE script entry per project (true today). When that changes, this
    # will need a smarter rewrite that preserves additional entries.
    text = re.sub(
        r'(\[project\.scripts\]\s*\n)([a-zA-Z_][a-zA-Z0-9_-]*)\s*=\s*"\2\.cli:main"',
        rf'\1{new_script_line}',
        text,
        count=1,
    )

    if text == original:
        log(f"  pyproject.toml: already matches brand (name={new_pkg_name})", quiet)
        return False

    path.write_text(text)
    log(f"  pyproject.toml: name='{new_pkg_name}', script='{brand.binary}'", quiet)
    return True


def load_presets(root: Path) -> dict:
    """Load scripts/brand_presets.json — the catalog of provider presets."""
    presets_path = root / "scripts" / "brand_presets.json"
    if not presets_path.exists():
        return {}
    data = json.loads(presets_path.read_text())
    # Strip leading _comment fields that aren't actual presets
    return {k: v for k, v in data.items() if not k.startswith("_")}


def generate_env_active(brand: BrandConfig, root: Path, quiet: bool) -> None:
    """Materialize .env-active from the api preset.

    .env-active is git-tracked AND brand-tracked; .env-secret holds the user's
    API key and is NOT tracked (per `.gitignore`).
    """
    presets = load_presets(root)
    preset_name = brand.api.preset
    preset = presets.get(preset_name)

    if preset is None:
        log(f"  .env-active: WARNING — unknown api.preset '{preset_name}', skipping (set base_url/model manually in .env-secret)", quiet)
        return

    # Brand can override the preset's defaults
    base_url = brand.api.base_url or preset.get("base_url")
    default_model = brand.api.model or preset.get("default_model")
    auth_env = preset.get("auth_env")

    lines: list[str] = [
        f"# .env-active — generated by scripts/build.py from brand.config.json",
        f"# Provider preset: {preset_name}",
        f"# DO NOT EDIT BY HAND — regenerated on every build.",
        f"# API keys live in .env-secret (which this file does NOT touch).",
        f"",
    ]

    if base_url:
        # litellm uses OPENAI_API_BASE / ANTHROPIC_API_BASE / etc; we pick the
        # most-universal var. litellm.completion(api_base=...) overrides this anyway.
        lines.append(f'export AION_API_BASE_URL="{base_url}"')
    if default_model:
        lines.append(f'export AION_MODEL="{default_model}"')
    if auth_env:
        lines.append(f'# Expected auth env var (set in .env-secret): {auth_env}=<your-api-key>')

    env_path = root / ".env-active"
    env_path.write_text("\n".join(lines) + "\n")
    log(f"  .env-active: generated for preset '{preset_name}'", quiet)


def build_wheel(root: Path, quiet: bool) -> int:
    """Build a wheel via `python -m build`. Returns subprocess exit code."""
    import subprocess

    log("  Building wheel via `python -m build`...", quiet)
    proc = subprocess.run(
        [sys.executable, "-m", "build", "--wheel"],
        cwd=root,
        capture_output=quiet,
    )
    if proc.returncode == 0:
        wheels = sorted((root / "dist").glob("*.whl"))
        if wheels:
            log(f"  built: {wheels[-1].name}", quiet)
    else:
        print(f"  wheel build failed (exit {proc.returncode})", file=sys.stderr)
    return proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser(description="Build aion from brand.config.json.")
    ap.add_argument("--wheel", action="store_true", help="Also build a wheel in dist/.")
    ap.add_argument("--quiet", "-q", action="store_true", help="Suppress informational output.")
    args = ap.parse_args()

    try:
        brand = load_brand_config(ROOT)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    log(f"[brand] {brand.display} {brand.version.label} (binary={brand.binary}, configDir={brand.config_dir}, modelIdentity={brand.model_identity.mode}, api={brand.api.preset})", args.quiet)

    update_pyproject(brand, ROOT, args.quiet)
    generate_env_active(brand, ROOT, args.quiet)

    if args.wheel:
        return build_wheel(ROOT, args.quiet)
    return 0


if __name__ == "__main__":
    sys.exit(main())
